# fly.toml app configuration file generated for quiet-water-5313 on 2023-07-25T15:18:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-water-5313"
primary_region = "ord"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
